/**
 * Brief step 2: what v7 has, screen by screen, and what the app has against it.
 *
 * Everything printed here is measured, not judged — screen labels and handler
 * counts come out of the prototype, routes out of the router, and the "built
 * from" column out of the header comment each stylesheet carries. Whether a
 * screen is actually faithful is a human call; this only says where to look.
 *
 * Usage: node tools/divergence-report.mjs [> docs/divergence.md]
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const PROTO = path.join(ROOT, 'project', 'Winterwork v7.dc.html');
const CLIENT = path.join(ROOT, 'app', 'client', 'src');

const html = fs.readFileSync(PROTO, 'utf8');

/**
 * Each screen is a <div data-screen-label="..."> inside its own <sc-if>.
 * Bounding by the next label would hand the last screen the whole remaining
 * file — the prototype's several thousand lines of JavaScript included — and
 * bounding by the first </sc-if> truncates every screen that has a nested one
 * (Session summary's records card, for instance). So the outer block is closed
 * by counting depth: we are already inside one sc-if at the label.
 */
function screens() {
  const marks = [...html.matchAll(/data-screen-label="([^"]+)"/g)];
  return marks.map((m) => {
    const tag = /<sc-if\b|<\/sc-if>/g;
    tag.lastIndex = m.index;
    let depth = 1;
    let end = html.length;
    for (let t; (t = tag.exec(html)); ) {
      depth += t[0] === '</sc-if>' ? -1 : 1;
      if (depth === 0) {
        end = t.index;
        break;
      }
    }
    const body = html.slice(m.index, end);
    return {
      label: m[1],
      lines: body.split('\n').length,
      handlers: (body.match(/onClick=/g) || []).length,
    };
  });
}

const routes = fs.readFileSync(path.join(CLIENT, 'App.tsx'), 'utf8');
const routePaths = [...routes.matchAll(/path="([^"]+)"/g)].map((m) => m[1]);

/**
 * The stylesheets say which prototype they were transcribed from, but in
 * comments scattered through the file rather than a header, so the whole file
 * is scanned.
 */
function builtFrom(file) {
  const p = path.join(CLIENT, 'screens', file);
  if (!fs.existsSync(p)) return null;
  const src = fs.readFileSync(p, 'utf8');
  const hits = new Set();
  for (const m of src.matchAll(/\bv([567])\b/g)) hits.add('v' + m[1]);
  return hits.size ? [...hits].sort().join('/') : 'unmarked';
}

/** v7 screen label -> the app stylesheet that covers it, where one exists. */
const SHEET = {
  Today: 'today.css', Habits: 'habits.css', 'Habit detail': 'habits.css',
  'Quit counter': 'quit.css', Progress: 'progress.css', Training: 'training.css',
  'Active session': 'training.css', 'Session summary': 'training.css',
  Exercise: 'training.css', 'Plan detail': 'programs.css',
  'Program detail': 'programs.css', Planner: 'planner.css', Focus: 'focus.css',
  'Focus history': 'focus.css', Mood: 'mood.css', Nutrition: 'nutrition.css',
  Street: 'street.css', Profile: null, Settings: null,
  Onboarding: 'onboarding.css', 'Fitness setup': 'onboarding.css',
  Welcome: 'auth.css', 'Sign in': 'auth.css', 'Create account': 'auth.css',
  'Forgot password': 'auth.css',
};

const rows = screens().sort((a, b) => b.handlers - a.handlers);
const totalHandlers = rows.reduce((n, r) => n + r.handlers, 0);

console.log('# Divergence report — v7 against the app\n');
console.log(`Generated by \`tools/divergence-report.mjs\`. v7 carries **${rows.length} screens**`);
console.log(`and **${totalHandlers} onClick handlers**.\n`);
console.log('`built from` is whichever prototype the stylesheet\'s own comments name.\n');
console.log('- `v6` — transcribed, but before the reference changed. It now has v7\'s');
console.log('  colours under a v6 layout, and has to be transcribed again.');
console.log('- `unmarked` — never transcribed from any prototype. This is the app\'s');
console.log('  own original implementation and has to be built from v7 outright.');
console.log('- `none` — no stylesheet at all; the screen does not exist yet.\n');
console.log('Read `built from` per stylesheet, not per screen: several screens share');
console.log('one sheet, so a screen inherits its neighbours\' marking. Exercise and');
console.log('Plan detail are the ones that flatter themselves this way — they share');
console.log('training.css and programs.css but were never transcribed.\n');
console.log('Handler counts are `onClick` attributes in the markup. They undercount:');
console.log('the prototype binds most behaviour through its state object, and');
console.log('`01_product_inventory.json` is the complete list.\n');
console.log('| v7 screen | lines | handlers | stylesheet | built from |');
console.log('| --- | ---: | ---: | --- | --- |');
for (const r of rows) {
  const sheet = SHEET[r.label];
  const from = sheet ? builtFrom(sheet) : null;
  console.log(
    `| ${r.label} | ${r.lines} | ${r.handlers} | ${sheet ?? '—'} | ${from ?? '**none**'} |`
  );
}
console.log(`\nRouter paths currently registered (${routePaths.length}): ` + routePaths.map((p) => `\`${p}\``).join(', '));
